Spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    
  application:
         name: PRODUCT-MICROSERVICES
     
Server:
  port: 8081
  
  
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  health:
    circuitbreakers:
      enabled: true
      
      
      
   
     
        
      
resilience4j:
  circuitbreaker:
    instances:
      productCircuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10
        permitted-number-of-calls-in-half-open-state: 10
  
     
  instance:
    hostname: localhost
     
          
     
